{% set name = "calibrated-explanations" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/calibrated_explanations-{{ version }}.tar.gz
  sha256: 77e8b41a7591c613240c9bba45083b539a742fbd85b507ac29b9cce47fadff8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - crepes
    - ipython
    - lime
    - matplotlib-base
    - numpy
    - pandas
    - venn-abers

test:
  imports:
    - calibrated_explanations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Extract calibrated explanations from machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Moffran/calibrated_explanations

extra:
  recipe-maintainers:
    - tuvelofstrom
