{% set name = "calibrated-explanations" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/calibrated_explanations-{{ version }}.tar.gz
  sha256: 43edc87f289a6a5cd17e2399df43d0c54a9e505b07110cc4a6cabe29de59139a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - crepes
    - ipython
    - lime
    - matplotlib-base
    - numpy
    - pandas
    - venn-abers

test:
  imports:
    - calibrated_explanations
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Extract calibrated explanations from machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Moffran/calibrated_explanations

extra:
  recipe-maintainers:
    - tuvelofstrom
