{% set name = "calibrated-explanations" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calibrated_explanations-{{ version }}.tar.gz
  sha256: 2cb463c81db62b26b4d8e747ff8a723d761f560c765a4c39233ef79280d904a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - cachetools
    - pympler
    - crepes
    - numpy
    - pandas
    - scikit-learn
    - pyyaml
    - venn-abers

test:
  imports:
    - calibrated_explanations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Extract calibrated explanations from machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Moffran/calibrated_explanations

extra:
  recipe-maintainers:
    - tuvelofstrom
