{% set name = "calibrated-explanations" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calibrated_explanations-{{ version }}.tar.gz
  sha256: db621258612fe9ca50c295c08c97b88c0aa02efe7b61157a5d14fc86f3f5191e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - cachetools
    - pympler
    - crepes
    - numpy
    - pandas
    - scikit-learn
    - pyyaml
    - venn-abers

test:
  imports:
    - calibrated_explanations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Extract calibrated explanations from machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Moffran/calibrated_explanations

extra:
  recipe-maintainers:
    - tuvelofstrom
