{% set name = "calibrated-explanations" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calibrated_explanations-{{ version }}.tar.gz
  sha256: d30c136ec40b76297f6b7f59bbfec20ca572b0500dba7866f9c78c678f01a269

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - crepes
    - ipython
    - lime
    - matplotlib-base
    - numpy
    - pandas
    - venn-abers

test:
  imports:
    - calibrated_explanations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Extract calibrated explanations from machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Moffran/calibrated_explanations

extra:
  recipe-maintainers:
    - tuvelofstrom
