name: Update meta.yaml

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-meta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml

    - name: Update meta.yaml
      run: python update_meta.py

    - name: Check for changes
      id: git_diff
      run: |
        git diff --exit-code recipe/meta.yaml
        echo "::set-output name=changed::$(echo $?)"

    - name: Commit and push changes
      if: steps.git_diff.outputs.changed != '0'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add recipe/meta.yaml
        git commit -m 'Update meta.yaml with latest version and sha256'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}